/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2021-02-01 16:11:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class success_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Sample JasperView</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function getReportName(){\r\n");
      out.write("\tvar value = document.getElementById(\"reportName\").value;\r\n");
      out.write("\tdocument.getElementById(\"reportUnit\").value = value;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function prepareFrame() {\r\n");
      out.write("    var ifrm = document.getElementById(\"frame\");\r\n");
      out.write("    ifrm.style.display=\"block\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"body\" leftmargin=\"20\" topmargin=\"0\"\r\n");
      out.write("\trightmargin=\"20\" bottommargin=\"0\" marginwidth=\"0\" marginheight=\"0\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t<form action=\"http://localhost:9797/jasperserver-pro/flow.html\" target=\"my-iframe\">\r\n");
      out.write("\r\n");
      out.write("\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>ReportName:</td>\r\n");
      out.write("\t\t\t\t<td><select id=\"reportName\" onchange=\"getReportName()\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"/Reports/ActiveUser\">ActiveUser</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"/Reports/TopSpenders_755\">TopSpenders_755</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"/Reports/Connector_Logs_by_Batch_755/Connector_Logs_by_Batch_755\">Connector_Logs_by_Batch_755</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"/Reports/CorporateCardListbyEmployee_755/CorporateCardListbyEmployee_755\">CorporateCardListbyEmployee_755</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"/Reports/Submitted_Reports_by_Org_755/Submitted_Reports_by_Org_755\">Submitted_Reports_by_Org_755</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"/Reports/User_Detail_List_755/User_Detail_List_755\">User_Detail_List_755</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"/Reports/ApprovedExpenseReport/ApprovedExpenseReport\">ApprovedExpenseReport</option>\r\n");
      out.write("\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr style=\"display:none\">\r\n");
      out.write("\t\t\t\t<td>PP:</td>\r\n");
      out.write("\t\t\t\t<td><input type='text' name='pp'\r\n");
      out.write("\t\t\t\t\tvalue=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr style=\"display:none\">\r\n");
      out.write("\t\t\t\t<td>screenPrefNsNames :</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name='screenPrefNsNames'\r\n");
      out.write("\t\t\t\t\tvalue='screenPrefs'></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr style=\"display:none\">\r\n");
      out.write("\t\t\t\t<td>userLocale:</td>\r\n");
      out.write("\t\t\t\t<td><input type='text' name='userLocale' value='en_US'>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr style=\"display:none\">\r\n");
      out.write("\t\t\t\t<td>showTerminatedEmployees:</td>\r\n");
      out.write("\t\t\t\t<td><input type='text' name='showTerminatedEmployees'\r\n");
      out.write("\t\t\t\t\tvalue='false'></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr style=\"display:none\">\r\n");
      out.write("\t\t\t\t<td>durFormat:</td>\r\n");
      out.write("\t\t\t\t<td><input type='text' name='durFormat'\r\n");
      out.write("\t\t\t\t\tvalue='duration_format_HM'></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr style=\"display:none\">\r\n");
      out.write("\t\t\t\t<td>_flowId:</td>\r\n");
      out.write("\t\t\t\t<td><input type='text' name='_flowId' value='viewReportFlow'>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>reportUnit:</td>\r\n");
      out.write("\t\t\t\t<td><input type='text' name='reportUnit' id='reportUnit'\r\n");
      out.write("\t\t\t\t\tvalue='/Reports/ActiveUser'></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr style=\"display:none\">\r\n");
      out.write("\t\t\t\t<td>who:</td>\r\n");
      out.write("\t\t\t\t<td><input type='text' name='who' value='EG#AP'></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- \t<tr>\r\n");
      out.write("\t\t\t\t<td>whenFrom:</td>\r\n");
      out.write("\t\t\t\t<td><input type='text' name='whenFrom' value='2020-12-20'>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>whenTo:</td>\r\n");
      out.write("\t\t\t\t<td><input type=text name='whenTo' value='2020-12-26'>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr style=\"display:none\">\r\n");
      out.write("\t\t\t\t<td>sumtotalDecorate:</td>\r\n");
      out.write("\t\t\t\t<td><input type='text' name='sumtotalDecorate' value='no'>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=2><input type=\"Submit\" value=\"Submit\" onclick=\"prepareFrame()\" class=\"btn btn-primary\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div width=\"100%\" height=\"100%\" style=\"display:none\" id=\"frame\">\r\n");
      out.write("\t <iframe name=\"my-iframe\" width=\"100%\" height=\"100%\"></iframe>\r\n");
      out.write("\t </div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
